name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# # Allows to run manually

#   workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Go to app folder
      run: cd final_demo
    - name: Install Compose
    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '2.14.2' # the full version of `docker-compose` command
    - name: Build the Docker image
      run: docker-compose up --build
